# Generated by Django 5.2.1 on 2026-04-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedRoute',
        ),
    ]
